workflows:
  flutter-workflow:
    name: Build Flutter APK
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        PROJECT_DIR: farm # Path to your Flutter project
    scripts:
      - name: Install dependencies
        script: |
          cd $PROJECT_DIR
          flutter pub get
      - name: Build APK
        script: |
          cd $PROJECT_DIR
          flutter build apk --release
    artifacts:
      - $PROJECT_DIR/build/app/outputs/flutter-apk/app-release.apk